src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    // Contient les différents attributs utilisés dans la base de données
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $cp = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    // Relation OneToMany de l'entité Employe
    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: Employe::class, orphanRemoval: true)]
    #[ORM\OrderBy(["nom" => "ASC"])]
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    // public function getDateCreationFr(): ?string {
    //     return $this->dateCreation->format('d-m-Y');
    // }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete(): ?string {
        return $this->adresse." ".$this->cp." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    // Toujours penser à utiliser __toString pour éviter l'erreur de conversion d'objet en string
    public function __toString() {
        return $this->raisonSociale;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            // Chaque champ du formulaire à un form type qui doit être renseigné en argument
            ->add('raisonSociale', TextType::class, [
                /* Pour améliorer l'aspect design des TextType on vas utiliser une class de bootstrap,
                on met en argumant un tableau avec comme option attr, qui accepte lui aussi un tableau,
                qui prend comme option une class qui se nomme form-control*/
                'attr' => [
                    'class' => 'form-control' 
                ]
            ])
            ->add('dateCreation', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control' 
                ]
            ])
            ->add('adresse', TextType::class, [
                'attr' => [
                    'class' => 'form-control' 
                ]
            ])
            ->add('cp', TextType::class, [
                'attr' => [
                    'class' => 'form-control' 
                ]
            ])
            ->add('ville', TextType::class, [
                'attr' => [
                    'class' => 'form-control' 
                ]
            ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success' 
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use Doctrine\ORM\EntityRepository;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    /* La route est le chemin de l'url (ex: 127.0.0.1:8000/entreprise) suivis d'un name 
    (ex : app_entreprise) pour afficher les éléments contenus dans la fonction,
    le name ne peut avoir un autre même nom identique, au risque de causer des problèmes de redirections */ 
    #[Route('/entreprise', name: 'app_entreprise')]
    // public function index(EntityManagerInterface $entityManager): Response
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        // $entreprises = $entityManager->getRepository(Entreprise::class)->findAll();
        // $entreprises = $entrepriseRepository->findAll();
        
        /* Le premier argument filtre ce que l'on souhaite afficher, cela équivaut à un 
        "SELECT * FROM entreprise WHERE ville = 'STRASBOURG' ORDER BY raisonSociale ASC"
        Le second argument du findBy équivaut à "SELECT * FROM entreprise ORDER BY raisonSociale ASC" */
        $entreprises = $entrepriseRepository->findBy([], ["raisonSociale" => "ASC"]);
        // Affiche sur la view donnée en premier argument, les éléments présents dans le tableau en second argument
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises
        ]);
    }

    #[Route('/entreprise/new', name: 'new_entreprise')]
    // Route pour éditer une entreprise par son id
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')]
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        // La valeur de $entreprise est null par défaut, si l'entreprise n'existe pas, on met une nouvelle Entreprise comme valeur
        if (!$entreprise) {
            $entreprise = new Entreprise();
        }
        
        $form = $this->createForm(EntrepriseType::class, $entreprise);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() retient les valeurs soumises
            // mais la variable $entreprise est également mise à jour
             $entreprise = $form->getData();
            
            /* persist dit à Doctrine de sauvegarder dans une instance l'objet en argument,
            équivaut à un prepare PDO */
            $entityManager->persist($entreprise);

            // Exécute la requête, équivaut à execute PDO
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        return $this->render('entreprise/new.html.twig', [
            'formAddEntreprise' => $form,
            'edit' => $entreprise->getId()
        ]);
    }

    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete(Entreprise $entreprise, EntityManagerInterface $entityManager) {
        $entityManager->remove($entreprise);
        $entityManager->flush();

        return $this->redirectToRoute('app_entreprise');
    }

    // Pour afficher un élément par rapport à un indentifiant, il faut ajouter dans l'url de la route '/{id}'
    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    public function show(Entreprise $entreprise): Response 
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise
        ]);
    }
}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %} {# Héritage de la view de base #}

{% block title %}Liste des entreprises{% endblock %}

{# Les commentaires dans un fichier twig se font avec une accolade et un dièse ouvrant et fermant #}
{# L'affichage du contenu d'une variable (exemple : un echo) sera mis entre deux accolades {{ }} #}

{# L'exécution d'élément logique, comme une condition ou une boucle, se fera dans une accolade et une deux symboles pourcentage
ouvrant et fermant {% %} pour le début de l'execution et pour la fin de l'exécution, exemple : 
{% for row in array %} {% endfor %} #}

{% block body %}
    <h1>Liste des entreprises</h1>

    <a href="{{ path('new_entreprise') }}" class="btn btn-success">Ajouter une entreprise</a><br/>
     {% for entreprise in entreprises %}
      {# Pour que tout fonctionne, il faut ajouter le paramètre id par chaînage #}
        <a href="{{ path('show_entreprise', {'id': entreprise.id}) }}">{{ entreprise }}</a>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id': entreprise.id}) }}">Edit</a>
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id': entreprise.id}) }}">Supp</a><br/>
     {% endfor %}

{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %} {# Héritage de la view de base #}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}
    {% if edit %}
        <h1>Editer une entreprise</h1>
    {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}
    

    {# {{ form(formAddEntreprise) }} #}

    {{ form_start(formAddEntreprise) }}
        {{ form_row(formAddEntreprise.raisonSociale)}}
        {{ form_row(formAddEntreprise.dateCreation)}}
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEntreprise.adresse)}}         
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.cp)}} 
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.ville)}} 
            </div>
        </div>
        {{ form_row(formAddEntreprise.valider)}}
    {{ form_end(formAddEntreprise) }}

{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %} {# Héritage de la view de base #}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}
    <h1>Détail d'une entreprise</h1>

    <h2>{{ entreprise }}</h2>

    <p>
       Adresse : {{ entreprise.adresseComplete}} <br/>
       {# On peut laisser twig s'occuper du formatage des dates sans passer par une méthode, en ajoutant un pipe "|" 
        suivi du filtre "date" avec dans la parenthèse le format voulu (voir la doc pour les autres filtres). #}
       Date de création {{ entreprise.dateCreation | date("d.m.Y") }}
    </p>

    <h3>Liste des employés de l'entreprise</h3>
    {% if entreprise.employes | length > 0 %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Employe</th>
                </tr>
            </thead>
            <tbody>
                {# Pour récupérer une liste il suffis d'appeler la collection correspondante à l'entité, 
                ici ce sera "employes" de l'entité Entreprise #}
                {% for employe in entreprise.employes %}
                <tr><td><a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }}</a></td></tr> <br/>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun salarié dans cette entreprise.</p>
    {% endif %}

    

{% endblock %}